### ISSUE TITLE
Current uploads tab lacks scrolling when plenty of files wre uploaded

### ISSUE THREAD

**Issue by birdli66** [linagora/linshare-ui-user#2]
Szenraio:
- Upload a larger amount of files (e.g. > 10)
- Open current uploads

Result:
Only the amount of files is visible that matches the size and resolution of the screen (i.e. 10 about 10 files)
To access the other files, the resolution of the screen needs to be increased or browser zoom-out must be used.

Minor issue in release 2.2.0.

**Comment by Klemele** [comment]
Hey @birdli66 , thanks for the feedback.

I just tried on Firefox 65.0 (64-bit)  & Chromium Version 71.0.3578.98.
I did not encounter this issue, so can you give me more informations about it ?

What I will need at minimum is the Web Browser name & version.
If you have some plugins or some special customisation of your Web Browser, please provide them to me to reproduce your testing environment as close as possible.

**Comment by birdli66** [comment]
FF 60.4.0esr (RHEL7)
FF 64.0.2 (Win10)
No plugins.
May be I was miss-understood: The problem is just a lacking paging control or a missing slider on #/files/upload/myspacem.

**Comment by Klemele** [comment]
Hi again,

I undestood you correctly the first time, but thanks for the precision :).

So I tried with the FF 60.4.0esr and I still got the scrolling bar in a bright orange color (see picture below)
![test-firefox-60 4 0esr](https://user-images.githubusercontent.com/6381993/52131147-5d7ee000-263c-11e9-8096-4ab816e42e8a.png)

So without aymore information, I don't know how to help you :/.

Anyway, here are my test setup:

- Ubuntu 18.04.1 LTS
- Firefox 60.4.0esr (64 bits)
- Linshare ui-user 2.2.0-SNAPSHOT (docker version)

**Comment by birdli66** [comment]
Let's leave it at that, it was not about helping me but helping you improve your product ;-)
We can live with the current setup, so from my PoV you can close this.
Thx for checking.
