### ISSUE TITLE
Long name is displayed weirdly in dropdown list

### ISSUE THREAD

**Issue by hanh-vu** [linagora/linshare-ui-user#3]
In LinShare
Version du produit : 2.2.0-1
Version du core : 2.2.0-1

Prepare an user with very long name
Upload a file to share with someone
Enter some key word to find the long name user in the dropdown list of the potential recipients
-> It doesn't appear properly there

**Comment by fmartin-linagora** [comment]
Hello,
Thank you for the report, I've created an issue and we will fix it asap.
Fred.

**Comment by fmartin-linagora** [comment]
related screenshot : https://user-images.githubusercontent.com/47238784/52108084-7df26e80-262b-11e9-8900-bf6f883cf6e6.png

**Comment by birdli66** [comment]
many thx

**Comment by marwanJebahi** [comment]
Hello,
The bug is fixed in 2.2.4 version, here is the changelog:
https://github.com/linagora/linshare/blob/master/CHANGELOG.md#224-2019-04-29-download-link
Regards
